## Import modules

In [1]:
import csv
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from IPython.display import display
import seaborn as sn  #Per heatmap
import time
import scipy as sp
import os

Audio-specific modules

In [2]:
import librosa as lb
import librosa.display

Sklearn modules

In [92]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.preprocessing import PolynomialFeatures, LabelEncoder,OneHotEncoder, StandardScaler, MinMaxScaler
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import GridSearchCV, ParameterGrid, train_test_split, cross_val_score
from sklearn.ensemble import RandomForestRegressor

## Load data

In [138]:
data = pd.read_csv('../data/development.csv', index_col=0) #### USA SEMPRE .././data/NOME_FILE o .././data/NOME_CARTELLA per accedere ai dati

In [139]:
data['path'] = data['path'].map(lambda x: x.split('/')[1])
#data = data.set_index('path')
display(data)

,sampling_rate,age,gender,ethnicity,mean_pitch,max_pitch,min_pitch,jitter,shimmer,energy,zcr_mean,spectral_centroid_mean,tempo,hnr,num_words,num_characters,num_pauses,silence_duration
path,,,,,,,,,,,,,,,,,,
1.wav,22050,24.0,female,arabic,1821.69060,3999.7170,145.43066,0.013795,0.082725,0.002254,0.210093,3112.257251,[151.99908088],-123.999726,69,281,39,23.846893
2.wav,22050,22.5,female,hungarian,1297.81870,3998.8590,145.37268,0.025349,0.096242,0.007819,0.078849,1688.016389,[129.19921875],-86.928478,69,281,21,19.388662
3.wav,22050,22.0,female,portuguese,1332.85240,3998.8025,145.42395,0.019067,0.119456,0.002974,0.105365,2576.901706,[117.45383523],-98.450670,69,281,1,21.640998
4.wav,22050,22.0,female,english,1430.34990,3998.4510,147.98083,0.017004,0.102389,0.022371,0.173701,3269.751413,[117.45383523],-56.459762,69,281,9,19.644127
5.wav,22050,22.0,male,dutch,1688.72340,3998.6113,145.44772,0.028027,0.124831,0.005369,0.107279,1930.897375,[112.34714674],-80.349204,69,281,11,18.041905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929.wav,22050,24.0,male,english,1641.14930,3999.1616,145.39359,0.023647,0.115361,0.001879,0.111799,2188.853478,[184.5703125],-100.921055,69,281,11,17.461406
2930.wav,22050,15.0,female,igbo,1089.60050,3984.6550,145.58409,0.015317,0.126740,0.000339,0.070508,2712.362323,[83.35433468],6.757283,0,0,1,1.509206
2931.wav,22050,17.0,female,igbo,994.46484,3989.1785,148.97475,0.009677,0.103535,0.001464,0.058442,2248.698477,[89.10290948],-53.913449,1,9,1,1.645034
2932.wav,22050,18.0,male,arabic,1600.00820,3999.7559,145.36101,0.019571,0.100946,0.004451,0.115139,1834.596924,[143.5546875],-96.143090,69,281,19,16.346848
2933.wav,22050,18.0,female,igbo,690.28046,3988.2874,149.26643,0.014833,0.096168,0.003675,0.042133,1440.227098,[83.35433468],-89.464755,0,0,4,2.275556

## Data Extraction

In [140]:
def load_data(audio_files, folder_path, sample_rate):
    time_stamps = []
    audio_arrays = {}
    mfccs = {}
    for file_name in audio_files:
        if file_name.endswith(".wav"):
            audio_array = lb.load(folder_path + file_name)
            trimmed_audio_array= lb.effects.trim(audio_array[0])
            time_stamps.append(len(trimmed_audio_array[0]))
            audio_arrays[file_name] = trimmed_audio_array[0]
            mfccs[file_name] = lb.feature.mfcc(y=trimmed_audio_array[0], sr=sample_rate, n_mfcc=15, n_fft=2048,hop_length=512)
    return (audio_arrays, mfccs, np.array(time_stamps))

In [141]:
def standardize_time_mfcc(mfcc,num_buckets):
    reduced_list =[]
    existing_int = mfcc.shape[1]
    for i in range(0,existing_int-(existing_int%num_buckets),existing_int//num_buckets):
        reduced_list.append(np.mean(mfcc[:, i:i+(mfcc.shape[1]//num_buckets)], axis=1).flatten())
    return np.array(reduced_list).transpose()

In [142]:
def standardize_all(mfcc_dict,num_buckets):
    standard_mfccs = {}
    for name, mfcc in mfcc_dict.items():
        standard_mfccs[name] = standardize_time_mfcc(mfcc,num_buckets)
    return standard_mfccs

In [143]:
def reshape_all(mfcc_dict):
    reshaped_mfccs = {}
    for name, mfcc in mfcc_dict.items():
        reshaped_mfccs[name] = mfcc.flatten()
    return pd.DataFrame(reshaped_mfccs).T

### Main

In [144]:
SAMPLE_RATE = 22050
num_time_buckets = 20

In [ ]:
audio_files = os.listdir('../data/audios_development')
audio_arrays,mfccs,time_sampl = load_data(audio_files, '../data/audios_development/', SAMPLE_RATE)

In [83]:
standardized_mfccs = standardize_all(mfccs, num_time_buckets)

In [89]:
reshaped_mfccs = reshape_all(standardized_mfccs)

In [90]:
display(reshaped_mfccs)

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
1.wav,-423.020538,-332.887329,-361.605164,-347.482208,-389.083527,-328.815033,-398.173309,-336.800690,-379.510284,-345.724213,...,-1.942417,-5.246557,-4.376464,0.120627,-5.158453,-1.831522,-3.805745,-3.881568,-4.000273,-8.090446
10.wav,-464.710785,-267.225800,-201.898865,-216.123856,-173.217758,-220.823898,-91.316536,-163.099533,-190.114258,-243.981277,...,4.086848,8.919844,12.513921,-1.471938,-5.042432,-2.831152,-1.790807,0.321547,1.039343,-6.841827
100.wav,-318.136597,-421.639404,-281.229004,-350.477203,-380.836121,-313.451111,-382.842468,-272.421265,-430.260315,-280.430054,...,-0.412136,2.075336,6.061966,6.569131,4.929160,3.960616,9.124262,10.854587,7.318303,9.405965
1000.wav,-396.088837,-338.936218,-441.260010,-421.752289,-436.263184,-393.596039,-496.009613,-445.108246,-517.327332,-557.111511,...,-0.204290,-18.454632,-7.708149,2.199664,-3.484957,-9.490080,-12.075005,-3.242330,-2.788409,-8.915504
1001.wav,-399.899261,-363.629517,-339.692078,-331.780243,-292.952393,-279.624115,-329.839478,-323.489655,-297.451721,-304.272430,...,-0.337629,-3.771065,-12.894007,-20.165813,-24.442867,-14.174511,-6.639238,-14.892796,-18.004873,-17.359259
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995.wav,-237.101822,-251.029114,-225.179825,-240.902634,-214.896286,-328.902344,-288.886658,-309.547485,-216.283569,-249.384491,...,-0.380812,5.354548,-7.917774,-6.913934,-12.418830,-6.988984,0.467288,-3.999441,4.249442,-0.261314
996.wav,-260.329346,-303.837067,-268.231964,-296.425598,-339.485199,-265.379089,-306.549103,-267.765625,-334.914368,-252.238235,...,1.907920,4.307010,6.263086,4.819046,6.840928,0.700918,4.721804,7.176890,6.416972,4.897392
997.wav,-253.112915,-137.904434,-214.022568,-279.082306,-233.791412,-256.458740,-281.646332,-233.430222,-238.886230,-231.248749,...,-15.474440,-9.980843,-12.830086,-9.290381,-5.878903,-2.367623,-8.148173,-0.053261,0.816683,-4.935268
998.wav,-396.649658,-330.637207,-297.137207,-334.702545,-309.985260,-382.760620,-281.101410,-342.125122,-270.877258,-336.018799,...,-7.688023,-12.178954,-8.236415,-5.629763,-8.098529,-6.090665,-4.651963,-11.114296,-4.836049,-4.849733
999.wav,-329.541504,-318.066437,-358.885864,-357.815674,-303.913788,-317.537506,-345.635620,-344.436035,-364.343292,-375.003662,...,-0.960991,2.276015,-12.166539,-14.509707,-7.698040,-2.841658,-4.972105,3.716316,4.689393,-4.430022

## Modelli

In [91]:
for col,imp in sorted(zip(reshaped_mfccs.columns, RandomForestRegressor(n_jobs=-1).fit(reshaped_mfccs, data['age']).feature_importances_*100), key=lambda x: x[1], reverse=True):
    print(col, '\t', imp)

201 	 1.0002899257826312
127 	 0.6851541290052747
195 	 0.6378358346196411
235 	 0.6370599910566298
189 	 0.6210777367783331
75 	 0.6179715611684038
211 	 0.5994434313727769
89 	 0.5851780757565556
249 	 0.5542294746435765
217 	 0.5505523511568658
79 	 0.5493339438494794
0 	 0.536654923821151
69 	 0.5309325690147406
272 	 0.5243477411578349
196 	 0.5237055223760564
118 	 0.5197279857107275
136 	 0.5178547364418885
83 	 0.5137317331228208
267 	 0.5104032678227961
84 	 0.5100935574913308
287 	 0.5087244159962194
66 	 0.5011055692286573
182 	 0.49774523303747636
221 	 0.4975280477154936
285 	 0.4940234508807234
70 	 0.49032747475715177
241 	 0.48935728704380943
92 	 0.47803903344286436
86 	 0.4677853415263154
37 	 0.4589230271141162
187 	 0.45579137412937265
179 	 0.4534785391324005
94 	 0.4531276943827125
72 	 0.45288422299763775
57 	 0.4515708956937492
13 	 0.44624865751737947
183 	 0.4436027641334228
68 	 0.44273270922899344
107 	 0.4379407963869428
218 	 0.43370514034014584
112 	 0.43361480076849557
177 	 0.42663129785795084
85 	 0.4249524045093383
106 	 0.4217447412192929
168 	 0.41696258148763743
20 	 0.41577106995916124
210 	 0.4151228141467073
297 	 0.41404510870926325
111 	 0.4111159615729912
269 	 0.41075122113800294
28 	 0.4097795246681248
208 	 0.4096113517679938
140 	 0.408113278536676
260 	 0.4072405723756083
205 	 0.4070877560366636
65 	 0.40681628018879856
163 	 0.4045225326969886
185 	 0.4032197070501382
139 	 0.4026838738533268
200 	 0.4020873705855835
125 	 0.40149832840848676
242 	 0.40122274912478995
227 	 0.4005374102639455
73 	 0.3967601547688968
283 	 0.395921330980492
251 	 0.3929387759321516
212 	 0.39272975277382727
294 	 0.3879809240062202
261 	 0.38747486530930914
97 	 0.3861603847360279
4 	 0.3848782531056371
291 	 0.3817613819100091
289 	 0.38130098965347287
29 	 0.3809657560509464
158 	 0.3806848855914022
129 	 0.3777486999198423
63 	 0.3760955436699677
30 	 0.3739005166950085
190 	 0.37295042136207995
76 	 0.372717646638891
165 	 0.3706496316900087
80 	 0.36835456625994323
105 	 0.36559169009096426
180 	 0.3650667646761003
198 	 0.3645747534139729
172 	 0.3642198888476203
54 	 0.36407303864847085
184 	 0.3619617845391489
293 	 0.36157279694182454
278 	 0.36119367566284294
3 	 0.35978655393345554
27 	 0.3591920687170178
230 	 0.3590302167861857
150 	 0.35889691995086936
238 	 0.3583295822698782
220 	 0.3580979713089624
152 	 0.35729582442059565
90 	 0.35679889912284585
31 	 0.3542278490564839
34 	 0.35366482691270956
259 	 0.3535278472689216
275 	 0.35333154586289606
12 	 0.35156858367869276
32 	 0.3493683044853889
296 	 0.3434503937715036
247 	 0.34250291272576716
142 	 0.341707167706202
216 	 0.3413010443459196
53 	 0.34129031768155177
120 	 0.3407890335125637
178 	 0.33898147615425983
226 	 0.33842239031234794
292 	 0.33609349542020217
33 	 0.3358517375148462
290 	 0.3351097075780377
193 	 0.3340476301384373
71 	 0.3337850403944233
74 	 0.3319633738950772
266 	 0.33167792516287153
254 	 0.3306992968603771
162 	 0.32937752355444827
44 	 0.32927435456269405
49 	 0.32894453273384555
10 	 0.3281334107731819
56 	 0.3275595220906411
240 	 0.3271222228201726
15 	 0.32710947538906
277 	 0.3266004827941729
43 	 0.32565849699103794
36 	 0.32559185097418114
35 	 0.32251690295604973
110 	 0.3222620588765776
250 	 0.32168600321194485
7 	 0.32108059812210077
113 	 0.31997170875159875
160 	 0.31944304538533563
167 	 0.3194277671532381
109 	 0.31894840613276115
274 	 0.31836440828930085
258 	 0.3178781552782152
26 	 0.31783443234988606
186 	 0.31757654755309916
42 	 0.31725930640174943
265 	 0.31651438783827457
115 	 0.3150744655792468
295 	 0.3142489190038194
209 	 0.31328109672672383
138 	 0.3123832484180932
229 	 0.31145825516303144
23 	 0.3113864266009059
256 	 0.3106901800256538
95 	 0.31040897292181546
271 	 0.30966531805753084
128 	 0.308938526461232
243 	 0.3082013555957919
215 	 0.30813961381231847
246 	 0.3077419595181818
119 	 0.30760689474511077
188 	 0.30757442010338343
45 	 0.30749781337037824
98 	 0.3069771610074819
154 	 0.3057761085387367
130 	 0.3057200640765465
237 	 0.3042566893983839
82 	 0.3041096052149495
286 	 0.30354283171761753
197 	 0.30335370541729306
171 	 0.3031671564106614
67 	 0.3016313712005791
9 	 0.30121890281441227
8 	 0.30111328085105926
88 	 0.30086003565172914
147 	 0.2998864983234691
175 	 0.2992307808654325
121 	 0.29842600909258227
5 	 0.2979525987471989
38 	 0.2970841156374578
93 	 0.29706133675230884
14 	 0.2964874041778163
134 	 0.2958012702875074
108 	 0.29569902904519424
1 	 0.2953487364938124
2 	 0.29441086230690117
231 	 0.294182831841188
214 	 0.29345986254918993
135 	 0.29207032963650004
55 	 0.29091265450514764
132 	 0.29079582182527836
52 	 0.28876495635233823
252 	 0.2884982099993595
181 	 0.2882023191931832
248 	 0.2879420286005332
149 	 0.2879028608979368
222 	 0.28680360944571726
144 	 0.28631713904858297
141 	 0.2861411695987001
255 	 0.28554370629897463
104 	 0.2848473112110098
78 	 0.284197789093605
155 	 0.28375310181632013
245 	 0.2837062468335987
46 	 0.28314314241549354
101 	 0.282919123783249
174 	 0.2814551779216231
114 	 0.2814231047055697
273 	 0.28088874397614616
161 	 0.2796627643811121
124 	 0.27959827485860367
47 	 0.2785569604497884
19 	 0.2785010882103209
100 	 0.2777271869366357
270 	 0.2776808109362445
280 	 0.27751364423285907
61 	 0.2767045649312454
213 	 0.2765514967236563
156 	 0.27614185250308276
117 	 0.27477374294857304
204 	 0.27383194465443506
199 	 0.27370725011809505
194 	 0.2730988168231489
298 	 0.27296973577392514
6 	 0.2728091303249795
148 	 0.2725870518957733
41 	 0.2719752605677026
99 	 0.2717953840304581
50 	 0.27076882809839486
18 	 0.2704694130568074
25 	 0.27014677853452007
225 	 0.2669713902412632
279 	 0.2643296615771165
48 	 0.26395242816710224
60 	 0.263592094633706
299 	 0.2630083206951145
16 	 0.2627064278342691
244 	 0.2624330219856892
102 	 0.26238401304187137
282 	 0.26164291062330725
116 	 0.2610048305491672
81 	 0.26073718044930777
176 	 0.25869338013296217
263 	 0.2584280482227284
64 	 0.25790762738003725
173 	 0.25788155665081913
257 	 0.25759108474973663
236 	 0.2575569521273471
146 	 0.2542788225564171
164 	 0.25315363392932205
234 	 0.25138009825924557
123 	 0.2501718515537196
87 	 0.24925145263778953
276 	 0.2487709594416779
224 	 0.24680062264274655
264 	 0.24664176939561436
191 	 0.24519528976717345
239 	 0.2446638192631883
223 	 0.2445267874461889
157 	 0.24158600843926045
151 	 0.24012381433271834
62 	 0.23998810358577286
153 	 0.23859612406433559
39 	 0.23787207469395058
206 	 0.23614597020230207
143 	 0.2352627092887907
219 	 0.23415855195809324
170 	 0.23371054586041462
288 	 0.2334429703449077
253 	 0.23120927091251153
103 	 0.23027320899890613
281 	 0.22504352223967178
228 	 0.22483284664097078
166 	 0.22467444670133882
233 	 0.22453239256914384
284 	 0.22402466273550914
192 	 0.2230520223738825
202 	 0.22266453582511736
17 	 0.22254786603010027
126 	 0.2215950208120565
96 	 0.21777784779204845
203 	 0.21676226633195633
22 	 0.21564757293117487
91 	 0.21418839580132198
24 	 0.21335374857703615
131 	 0.2126213619295157
137 	 0.2122397449904749
11 	 0.21167631656971564
232 	 0.2111172959636132
59 	 0.21074252012195466
268 	 0.20838896940324772
77 	 0.20569919171435444
262 	 0.20362609499772233
58 	 0.19813602007131295
40 	 0.19486282334166352
159 	 0.19424711923200638
169 	 0.1938135444585985
207 	 0.19152362393854033
21 	 0.1849366137795583
133 	 0.1844860268849334
51 	 0.18261199652352153
145 	 0.17884914905460736
122 	 0.17433549278577995

In [93]:
cross_val_score(RandomForestRegressor(n_jobs=-1), reshaped_mfccs, data['age'], cv=5, scoring='neg_mean_absolute_error').mean()

np.float64(-10.549830251292219)

## Esperimenti random

In [114]:
sentence_feat = data.loc[:,['num_words','num_characters']].values
uniq, ind, count= np.unique(np.array(sentence_feat), return_counts=True, return_inverse=True, axis=0)
display(count)

array([ 409,    2,    1,   39,    8,    5,    2,    3,    3,    3,    1,
          8,    5,   19,    9,   16,    7,    7,    1,    4,    1,    2,
          9,    8,   27,   66,   26,    6,    5,    7,    2,   58,    1,
         52,   56,    6,   51,    5,    9,    4,    8,    4,    1,    2,
          3,    3,   15,    1,    6,    2,   28,    3,   55,   28,    3,
          1,   44,    1,    1,    5,    4,    5,    1,    1,    1,    2,
          6,    3,   11,   16,    1,    1,    1,    1,    1,    1, 1710])

In [161]:
print(uniq[-1])

[ 69 281]

In [145]:
long_data = data[ind==76]
display(long_data)

,sampling_rate,age,gender,ethnicity,mean_pitch,max_pitch,min_pitch,jitter,shimmer,energy,zcr_mean,spectral_centroid_mean,tempo,hnr,num_words,num_characters,num_pauses,silence_duration
path,,,,,,,,,,,,,,,,,,
1.wav,22050,24.0,female,arabic,1821.69060,3999.7170,145.43066,0.013795,0.082725,0.002254,0.210093,3112.257251,[151.99908088],-123.999726,69,281,39,23.846893
2.wav,22050,22.5,female,hungarian,1297.81870,3998.8590,145.37268,0.025349,0.096242,0.007819,0.078849,1688.016389,[129.19921875],-86.928478,69,281,21,19.388662
3.wav,22050,22.0,female,portuguese,1332.85240,3998.8025,145.42395,0.019067,0.119456,0.002974,0.105365,2576.901706,[117.45383523],-98.450670,69,281,1,21.640998
4.wav,22050,22.0,female,english,1430.34990,3998.4510,147.98083,0.017004,0.102389,0.022371,0.173701,3269.751413,[117.45383523],-56.459762,69,281,9,19.644127
5.wav,22050,22.0,male,dutch,1688.72340,3998.6113,145.44772,0.028027,0.124831,0.005369,0.107279,1930.897375,[112.34714674],-80.349204,69,281,11,18.041905
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2924.wav,22050,27.0,female,czech,817.82214,3998.9214,145.37355,0.029751,0.121434,0.009271,0.077740,1583.356491,[112.34714674],-89.199463,69,281,1,24.215828
2926.wav,22050,22.0,female,albanian,1457.88110,3999.0474,145.45604,0.015260,0.087883,0.003336,0.135405,2005.046430,[92.28515625],-108.632687,69,281,18,17.925805
2928.wav,22050,39.0,female,fijian,1122.14280,3999.1540,145.44153,0.027051,0.126792,0.008059,0.111901,1861.406972,[103.359375],-67.774090,69,281,1,29.892472
2929.wav,22050,24.0,male,english,1641.14930,3999.1616,145.39359,0.023647,0.115361,0.001879,0.111799,2188.853478,[184.5703125],-100.921055,69,281,11,17.461406
2932.wav,22050,18.0,male,arabic,1600.00820,3999.7559,145.36101,0.019571,0.100946,0.004451,0.115139,1834.596924,[143.5546875],-96.143090,69,281,19,16.346848

In [146]:
short_data = data[ind!=76]
display(short_data)

,sampling_rate,age,gender,ethnicity,mean_pitch,max_pitch,min_pitch,jitter,shimmer,energy,zcr_mean,spectral_centroid_mean,tempo,hnr,num_words,num_characters,num_pauses,silence_duration
path,,,,,,,,,,,,,,,,,,
8.wav,22050,18.0,female,igbo,1042.95260,3989.9595,147.18710,0.013859,0.104579,0.000908,0.111858,2701.802811,[215.33203125],5.586937,4,16,1,1.367937
9.wav,22050,18.0,female,igbo,779.33765,2927.2144,157.62047,0.013921,0.080848,0.000324,0.039097,1448.093479,[143.5546875],-43.823950,0,0,1,1.989660
10.wav,22050,18.0,male,igbo,732.35297,3988.0715,147.95331,0.017735,0.114380,0.007425,0.073166,1722.624247,[86.1328125],-47.044540,5,22,1,1.437914
14.wav,22050,20.0,female,igbo,1470.73180,3994.0364,147.56389,0.012966,0.064988,0.002256,0.076528,2186.139030,[92.28515625],-16.998423,4,12,1,1.093379
15.wav,22050,20.0,male,igbo,821.28864,3533.2290,150.64523,0.016953,0.107844,0.003589,0.043305,1833.282572,[107.66601562],-60.091181,0,0,1,0.668345
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925.wav,22050,18.0,male,igbo,495.67523,1235.3107,148.78967,0.050740,0.170841,0.004776,0.022993,692.116731,[135.99917763],-30.340135,0,0,1,1.529025
2927.wav,22050,32.0,male,igbo,588.56006,3247.9130,146.66269,0.015273,0.073947,0.025475,0.048158,2039.953197,[234.90767045],-48.841359,4,15,2,3.041814
2930.wav,22050,15.0,female,igbo,1089.60050,3984.6550,145.58409,0.015317,0.126740,0.000339,0.070508,2712.362323,[83.35433468],6.757283,0,0,1,1.509206
2931.wav,22050,17.0,female,igbo,994.46484,3989.1785,148.97475,0.009677,0.103535,0.001464,0.058442,2248.698477,[89.10290948],-53.913449,1,9,1,1.645034
2933.wav,22050,18.0,female,igbo,690.28046,3988.2874,149.26643,0.014833,0.096168,0.003675,0.042133,1440.227098,[83.35433468],-89.464755,0,0,4,2.275556

## Features

In [147]:
data.loc[ind==76,'ethnicity'] = 1
data.loc[ind!=76,'ethnicity'] = 0
clean_data = data.drop(columns=['num_words','num_characters','num_pauses','sampling_rate','max_pitch','min_pitch'])
clean_data['tempo'] = clean_data['tempo'].map(lambda x: float(x[1:-1]))
display(clean_data)

,age,gender,ethnicity,mean_pitch,jitter,shimmer,energy,zcr_mean,spectral_centroid_mean,tempo,hnr,silence_duration
path,,,,,,,,,,,,
1.wav,24.0,female,1,1821.69060,0.013795,0.082725,0.002254,0.210093,3112.257251,151.999081,-123.999726,23.846893
2.wav,22.5,female,1,1297.81870,0.025349,0.096242,0.007819,0.078849,1688.016389,129.199219,-86.928478,19.388662
3.wav,22.0,female,1,1332.85240,0.019067,0.119456,0.002974,0.105365,2576.901706,117.453835,-98.450670,21.640998
4.wav,22.0,female,1,1430.34990,0.017004,0.102389,0.022371,0.173701,3269.751413,117.453835,-56.459762,19.644127
5.wav,22.0,male,1,1688.72340,0.028027,0.124831,0.005369,0.107279,1930.897375,112.347147,-80.349204,18.041905
...,...,...,...,...,...,...,...,...,...,...,...,...
2929.wav,24.0,male,1,1641.14930,0.023647,0.115361,0.001879,0.111799,2188.853478,184.570312,-100.921055,17.461406
2930.wav,15.0,female,0,1089.60050,0.015317,0.126740,0.000339,0.070508,2712.362323,83.354335,6.757283,1.509206
2931.wav,17.0,female,0,994.46484,0.009677,0.103535,0.001464,0.058442,2248.698477,89.102909,-53.913449,1.645034
2932.wav,18.0,male,1,1600.00820,0.019571,0.100946,0.004451,0.115139,1834.596924,143.554688,-96.143090,16.346848
2933.wav,18.0,female,0,690.28046,0.014833,0.096168,0.003675,0.042133,1440.227098,83.354335,-89.464755,2.275556

In [149]:
full_data = pd.concat([clean_data, reshaped_mfccs], axis=1)
display(full_data)

,age,gender,ethnicity,mean_pitch,jitter,shimmer,energy,zcr_mean,spectral_centroid_mean,tempo,...,290,291,292,293,294,295,296,297,298,299
1.wav,24.0,female,1,1821.69060,0.013795,0.082725,0.002254,0.210093,3112.257251,151.999081,...,-1.942417,-5.246557,-4.376464,0.120627,-5.158453,-1.831522,-3.805745,-3.881568,-4.000273,-8.090446
2.wav,22.5,female,1,1297.81870,0.025349,0.096242,0.007819,0.078849,1688.016389,129.199219,...,1.602238,-4.590589,1.433791,0.820234,2.581253,2.410373,-4.295688,4.829690,-2.975813,0.896594
3.wav,22.0,female,1,1332.85240,0.019067,0.119456,0.002974,0.105365,2576.901706,117.453835,...,3.076923,-4.109672,-0.462944,1.148665,2.150095,-0.915860,-1.507109,2.374164,4.178719,3.131405
4.wav,22.0,female,1,1430.34990,0.017004,0.102389,0.022371,0.173701,3269.751413,117.453835,...,-5.853500,-16.481180,-12.324727,-15.200755,-9.736434,-11.306305,-17.313793,-11.241422,-13.679470,-18.686422
5.wav,22.0,male,1,1688.72340,0.028027,0.124831,0.005369,0.107279,1930.897375,112.347147,...,6.182858,-0.351926,5.084396,8.022604,6.370649,2.164866,6.037231,3.468850,5.418577,9.559019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2929.wav,24.0,male,1,1641.14930,0.023647,0.115361,0.001879,0.111799,2188.853478,184.570312,...,2.097236,-0.667882,2.911166,3.991309,3.089388,0.143708,1.004856,-3.498344,0.469718,0.205209
2930.wav,15.0,female,0,1089.60050,0.015317,0.126740,0.000339,0.070508,2712.362323,83.354335,...,-1.984530,4.366840,-2.148508,-1.667701,2.311760,1.714393,6.971056,3.783729,-4.724131,-4.516420
2931.wav,17.0,female,0,994.46484,0.009677,0.103535,0.001464,0.058442,2248.698477,89.102909,...,-4.999870,-11.469429,-10.364605,-11.625636,-0.410724,-13.186292,-10.333710,-2.208193,-1.970908,-3.222235
2932.wav,18.0,male,1,1600.00820,0.019571,0.100946,0.004451,0.115139,1834.596924,143.554688,...,5.136696,2.013695,2.777900,-0.552682,-0.650282,-4.115758,0.530575,-2.299961,-3.592226,1.672502
2933.wav,18.0,female,0,690.28046,0.014833,0.096168,0.003675,0.042133,1440.227098,83.354335,...,6.029294,9.587608,4.154411,1.088154,4.204056,-5.600774,-1.497502,6.961174,3.605214,6.599584

In [150]:
female_full_data = full_data[full_data['gender']=='female'].drop(columns=['gender'])
male_full_data = full_data[full_data['gender']=='male'].drop(columns=['gender'])
display(female_full_data)
display(male_full_data)

,age,ethnicity,mean_pitch,jitter,shimmer,energy,zcr_mean,spectral_centroid_mean,tempo,hnr,...,290,291,292,293,294,295,296,297,298,299
1.wav,24.0,1,1821.69060,0.013795,0.082725,0.002254,0.210093,3112.257251,151.999081,-123.999726,...,-1.942417,-5.246557,-4.376464,0.120627,-5.158453,-1.831522,-3.805745,-3.881568,-4.000273,-8.090446
2.wav,22.5,1,1297.81870,0.025349,0.096242,0.007819,0.078849,1688.016389,129.199219,-86.928478,...,1.602238,-4.590589,1.433791,0.820234,2.581253,2.410373,-4.295688,4.829690,-2.975813,0.896594
3.wav,22.0,1,1332.85240,0.019067,0.119456,0.002974,0.105365,2576.901706,117.453835,-98.450670,...,3.076923,-4.109672,-0.462944,1.148665,2.150095,-0.915860,-1.507109,2.374164,4.178719,3.131405
4.wav,22.0,1,1430.34990,0.017004,0.102389,0.022371,0.173701,3269.751413,117.453835,-56.459762,...,-5.853500,-16.481180,-12.324727,-15.200755,-9.736434,-11.306305,-17.313793,-11.241422,-13.679470,-18.686422
6.wav,33.0,1,1258.52160,0.025642,0.093994,0.014001,0.152036,2350.747577,123.046875,-93.453230,...,-8.174415,-8.913464,-10.072395,-13.084078,-4.271658,-6.493922,-6.987832,-6.430759,-6.534220,-4.162319
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2926.wav,22.0,1,1457.88110,0.015260,0.087883,0.003336,0.135405,2005.046430,92.285156,-108.632687,...,0.226774,2.290264,-2.824454,2.356261,1.796209,1.618824,-0.084660,-1.098554,-2.280983,-0.979584
2928.wav,39.0,1,1122.14280,0.027051,0.126792,0.008059,0.111901,1861.406972,103.359375,-67.774090,...,5.125805,4.725461,3.795096,7.323720,7.526706,3.167778,1.359615,-0.664699,6.014208,5.774710
2930.wav,15.0,0,1089.60050,0.015317,0.126740,0.000339,0.070508,2712.362323,83.354335,6.757283,...,-1.984530,4.366840,-2.148508,-1.667701,2.311760,1.714393,6.971056,3.783729,-4.724131,-4.516420
2931.wav,17.0,0,994.46484,0.009677,0.103535,0.001464,0.058442,2248.698477,89.102909,-53.913449,...,-4.999870,-11.469429,-10.364605,-11.625636,-0.410724,-13.186292,-10.333710,-2.208193,-1.970908,-3.222235
2933.wav,18.0,0,690.28046,0.014833,0.096168,0.003675,0.042133,1440.227098,83.354335,-89.464755,...,6.029294,9.587608,4.154411,1.088154,4.204056,-5.600774,-1.497502,6.961174,3.605214,6.599584

,age,ethnicity,mean_pitch,jitter,shimmer,energy,zcr_mean,spectral_centroid_mean,tempo,hnr,...,290,291,292,293,294,295,296,297,298,299
5.wav,22.0,1,1688.72340,0.028027,0.124831,0.005369,0.107279,1930.897375,112.347147,-80.349204,...,6.182858,-0.351926,5.084396,8.022604,6.370649,2.164866,6.037231,3.468850,5.418577,9.559019
7.wav,18.0,1,1789.02590,0.022059,0.138322,0.001402,0.177713,2771.793237,92.285156,-132.864988,...,-1.061666,-5.589748,-3.439590,0.449181,-0.561726,-3.568505,-0.205955,-1.555035,-2.410590,-3.159631
10.wav,18.0,0,732.35297,0.017735,0.114380,0.007425,0.073166,1722.624247,86.132812,-47.044540,...,4.086848,8.919844,12.513921,-1.471938,-5.042432,-2.831152,-1.790807,0.321547,1.039343,-6.841827
11.wav,28.0,1,1111.25890,0.021592,0.102127,0.005962,0.080557,1822.927444,123.046875,-84.304087,...,-2.362653,-4.836688,-3.237507,0.298921,-0.370968,-3.000236,-3.164778,-0.859076,-7.226579,-2.283674
12.wav,20.0,1,1331.60960,0.015685,0.104188,0.004787,0.141055,2297.955649,117.453835,-86.256958,...,-7.345084,1.630896,2.389131,1.143206,-1.852906,-0.740636,4.637617,-3.854735,6.035574,-6.804972
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2923.wav,22.0,1,1732.70870,0.019848,0.114089,0.003877,0.186958,2832.177810,172.265625,-94.335132,...,-18.264940,-12.389527,-12.179855,-13.496652,-14.648852,-10.948323,-13.115424,-16.638103,-11.601784,-9.497545
2925.wav,18.0,0,495.67523,0.050740,0.170841,0.004776,0.022993,692.116731,135.999178,-30.340135,...,-13.244773,1.092194,-12.603058,-17.293257,-13.418323,-16.404589,-22.299887,-20.639952,-9.139045,-3.552170
2927.wav,32.0,0,588.56006,0.015273,0.073947,0.025475,0.048158,2039.953197,234.907670,-48.841359,...,-2.113768,-6.372054,-11.992163,3.262146,-8.659460,-4.427877,-1.516657,-7.313030,-14.316506,-11.982656
2929.wav,24.0,1,1641.14930,0.023647,0.115361,0.001879,0.111799,2188.853478,184.570312,-100.921055,...,2.097236,-0.667882,2.911166,3.991309,3.089388,0.143708,1.004856,-3.498344,0.469718,0.205209
2932.wav,18.0,1,1600.00820,0.019571,0.100946,0.004451,0.115139,1834.596924,143.554688,-96.143090,...,5.136696,2.013695,2.777900,-0.552682,-0.650282,-4.115758,0.530575,-2.299961,-3.592226,1.672502

## Modello female

In [ ]:
female = female_full_data.drop(columns=['age'])
female.columns = female.columns.astype(str)
female_age = female_full_data['age']
for col,imp in sorted(zip(female.columns, RandomForestRegressor(n_jobs=-1).fit(female, female_age).feature_importances_*100), key=lambda x: x[1], reverse=True):
    print(col, '\t', imp)

silence_duration 	 30.976482907357152
hnr 	 1.9092025567546393
shimmer 	 1.0969811815695811
128 	 1.0592713544892232
83 	 0.8746076655902851
67 	 0.7254095977085506
71 	 0.6512736424909275
170 	 0.6510293125124328
178 	 0.6119758250197623
84 	 0.5723653655715686
239 	 0.550670883083401
135 	 0.5225951257544973
165 	 0.5178851582734602
246 	 0.5042248212044818
22 	 0.49980812564145055
64 	 0.48935307566054215
162 	 0.48478823904035534
164 	 0.47430239558924137
jitter 	 0.45328522257982484
89 	 0.4468523505094188
189 	 0.445869515117981
122 	 0.4441056720757764
151 	 0.4429046801878135
5 	 0.440703606920438
58 	 0.4392472864260792
127 	 0.43600244242628816
140 	 0.43480330571629017
160 	 0.4327839358675264
23 	 0.42526190920670387
11 	 0.4108655403839528
228 	 0.40485708229718415
zcr_mean 	 0.40194710118348587
208 	 0.3997247586252061
123 	 0.39935236750552683
209 	 0.376349216479161
267 	 0.3642899196356134
37 	 0.3601382399627516
276 	 0.35903440831864336
0 	 0.3472027135684856
124 	 0.3430814268316845
70 	 0.3397507055041649
214 	 0.33500809112574825
219 	 0.33106580311322953
18 	 0.3261924198130354
29 	 0.3253446265541846
12 	 0.3247621338185501
262 	 0.3225599029735082
136 	 0.32249624269147664
132 	 0.31798771947414817
131 	 0.31599641802335865
1 	 0.3157175805330945
spectral_centroid_mean 	 0.3150923869074446
81 	 0.3101125855675966
15 	 0.3098824829686161
284 	 0.294906973203777
69 	 0.29448088926118526
206 	 0.2906101580953783
16 	 0.28973253908508717
75 	 0.28893822457118995
13 	 0.286309508701875
179 	 0.284547294755944
147 	 0.28357657988968316
108 	 0.2823858472950185
207 	 0.2735909931289423
92 	 0.2717957723578083
291 	 0.27141818959238734
energy 	 0.2700313303440146
tempo 	 0.2630799042733572
43 	 0.2620073027256761
79 	 0.2617108647028676
61 	 0.2603083940596031
57 	 0.2600444358616946
196 	 0.2552216005429027
261 	 0.25255557605026585
282 	 0.25192750786877655
63 	 0.24872214808272722
137 	 0.24694715507827414
38 	 0.2464208635110477
21 	 0.24542606150680665
148 	 0.2453577783214413
3 	 0.24517361280204383
17 	 0.24507600458392598
31 	 0.24139028516071193
163 	 0.24099958802216778
190 	 0.24068269330195805
72 	 0.24036655743760585
236 	 0.23830017305484286
73 	 0.23711152182735337
221 	 0.23670895696531355
100 	 0.23441537923138966
249 	 0.23424735894555468
87 	 0.2338310399621637
277 	 0.23382105645478815
114 	 0.23370146243986475
90 	 0.23228590922831754
32 	 0.2320033987362182
201 	 0.2319198005652019
210 	 0.23141327520184723
138 	 0.23135924532420576
129 	 0.23125071590798651
76 	 0.2298359477478226
264 	 0.22654597739102003
42 	 0.22636754943301698
271 	 0.22596962005827395
24 	 0.2253544593724807
39 	 0.2247927840890731
187 	 0.2242161911707537
25 	 0.2220901840103424
139 	 0.22200805387757588
269 	 0.2190238439514129
297 	 0.21862441049829376
126 	 0.21507743271933366
240 	 0.2145170819847698
8 	 0.21155877282147728
149 	 0.2105514725890685
193 	 0.20913301640888382
115 	 0.20791399999920723
278 	 0.2073956438266341
80 	 0.20693544357027557
94 	 0.20571676899895092
198 	 0.2052282681384226
153 	 0.20502208780764072
20 	 0.20452244665246055
141 	 0.20309211679708583
253 	 0.20117424221848224
88 	 0.20087670050760445
168 	 0.20060191434217192
195 	 0.20044837079359065
157 	 0.20027975543729484
279 	 0.19987718936072524
150 	 0.19910374189239607
283 	 0.19870281188961403
235 	 0.1984048262876717
121 	 0.19800120169786461
234 	 0.19767673345008596
49 	 0.19678763771662355
44 	 0.1965915727447718
169 	 0.1960211567048291
273 	 0.19572501984760926
285 	 0.19531839963472017
237 	 0.19451645913944432
268 	 0.1942927390124153
26 	 0.19397327938462955
197 	 0.19316546423975398
266 	 0.19154730618371252
292 	 0.19124990009135537
30 	 0.1910246862205828
296 	 0.18883416924849195
232 	 0.1875321436979887
19 	 0.1868334137150574
93 	 0.1860367921456439
111 	 0.18419633833790533
95 	 0.18333857701187106
9 	 0.18124889638901423
185 	 0.17782979434026522
245 	 0.17779420349645825
181 	 0.17662566818385844
65 	 0.1761987932102308
33 	 0.17486096551070826
120 	 0.17352622298990333
243 	 0.1732803027897252
4 	 0.1707462160001947
62 	 0.16993461182340272
145 	 0.16979365893206555
220 	 0.16946774816697932
231 	 0.16932918024414392
180 	 0.16830009492166265
244 	 0.16818276280223507
52 	 0.16780897345472662
48 	 0.167697315986459
55 	 0.16717132882655103
6 	 0.16687907284846454
146 	 0.16675959851185063
242 	 0.16623372377678278
118 	 0.1646373417653516
176 	 0.16370219424439206
28 	 0.16333772285624526
295 	 0.163027556814731
248 	 0.16273596308440588
260 	 0.16193445884079474
280 	 0.16183822545545043
77 	 0.16180335456884748
254 	 0.1607512707743448
225 	 0.160456496163291
255 	 0.15977338006458391
222 	 0.15934779720656328
56 	 0.1586567405168376
226 	 0.15843249902337808
161 	 0.1583957111453595
213 	 0.15782946483727064
175 	 0.15696766980648474
97 	 0.15627641763749633
66 	 0.15537986256177583
117 	 0.15514724509660183
247 	 0.15481603318991466
103 	 0.15470331203644136
14 	 0.15465571386617324
40 	 0.15419741899082323
156 	 0.1537473313790199
144 	 0.1533496014931071
205 	 0.152994575893424
36 	 0.152915886012989
50 	 0.15259842854029484
167 	 0.15248772304383515
200 	 0.15229951921826942
86 	 0.15213739450560324
41 	 0.151049470624576
191 	 0.15059387236732916
35 	 0.15036608799782433
202 	 0.14912867519683784
10 	 0.1490578499072577
215 	 0.1489772835793374
107 	 0.1489013568568534
298 	 0.1482692353486154
174 	 0.1482403909536517
130 	 0.14571285439916615
270 	 0.1452744219534437
51 	 0.14521824023440547
68 	 0.14498555378133715
27 	 0.1430755209795255
218 	 0.14241841812641629
102 	 0.14204707599208105
275 	 0.14105646769801708
154 	 0.1408122726616239
166 	 0.14050186851015417
256 	 0.13969595783814545
183 	 0.13877892907940784
152 	 0.13851753290632274
59 	 0.1385093943120205
60 	 0.1380159416513089
74 	 0.137536505437569
mean_pitch 	 0.13541848250120758
46 	 0.13422088867030338
113 	 0.1340746975995931
184 	 0.13313268234771894
172 	 0.13305339072304434
238 	 0.13267639604353548
7 	 0.1323019334284393
250 	 0.1322565109411422
45 	 0.13143402079373542
116 	 0.13118749937254942
211 	 0.13013089147988366
204 	 0.1292721197398341
216 	 0.1292579251689591
134 	 0.1286096314503131
177 	 0.12856476464267402
203 	 0.1281896601641422
155 	 0.12739893007030795
182 	 0.127206351563406
188 	 0.1269277975295398
199 	 0.1264976985985263
259 	 0.1258188093796699
91 	 0.12560400348083603
78 	 0.12505993175964125
281 	 0.12389384664878209
158 	 0.12377448757578152
227 	 0.12358989730187771
171 	 0.12276008391643893
230 	 0.1223372862313998
133 	 0.12221973927063591
263 	 0.12144649177797338
265 	 0.1211328915943562
290 	 0.1200546162945438
99 	 0.11991933066719104
224 	 0.11858067020170296
53 	 0.11670270502379945
229 	 0.1160769405933351
194 	 0.11415188579426987
212 	 0.11385325651260753
186 	 0.11304886183161464
241 	 0.11287135074157367
252 	 0.10985977566058326
287 	 0.10971851866255763
274 	 0.10867696832396792
217 	 0.10850336092699935
286 	 0.10787587460893994
98 	 0.10780034939188116
125 	 0.10453850751695468
173 	 0.10431576780730781
101 	 0.10271339491500708
112 	 0.10218655880014055
294 	 0.10101277712217245
34 	 0.10084106358579682
82 	 0.10001771288279913
272 	 0.09873931036987185
110 	 0.09667031809079366
106 	 0.09637729891874137
289 	 0.09630132888428884
2 	 0.09546534283847395
293 	 0.09461923875365492
257 	 0.09348184002185524
192 	 0.09313537806985399
109 	 0.09279813071945679
223 	 0.0927429793349248
104 	 0.09110345842905976
159 	 0.08799567885342986
105 	 0.08771900601584684
47 	 0.08617567035113585
233 	 0.08546212006250785
258 	 0.08366411797523164
96 	 0.07994657077560717
85 	 0.07972594907703537
119 	 0.07954583400727566
143 	 0.07942356828848296
251 	 0.07824587487111458
288 	 0.0773060770693289
299 	 0.07433230307804199
54 	 0.07256717456350259
142 	 0.06117090690030207
ethnicity 	 0.0001728327192562869

In [153]:
cross_val_score(RandomForestRegressor(n_jobs=-1), female, female_age, cv=10, scoring='neg_mean_absolute_error').mean()

np.float64(-7.384200214332308)

## Modello male

In [154]:
male = male_full_data.drop(columns=['age'])
male.columns = male.columns.astype(str)
male_age = male_full_data['age']
for col,imp in sorted(zip(male.columns, RandomForestRegressor(n_jobs=-1).fit(male, male_age).feature_importances_*100), key=lambda x: x[1], reverse=True):
    print(col, '\t', imp)

silence_duration 	 22.217247700433912
121 	 1.655527569636188
183 	 1.4933259853015912
100 	 1.318286952007992
hnr 	 1.2249401595452882
40 	 0.9171493337123302
jitter 	 0.8472681910209544
146 	 0.7786669200119974
94 	 0.7462382604154416
148 	 0.6982977221113095
190 	 0.6249264280612189
120 	 0.5898414404647836
86 	 0.5738555072929864
196 	 0.5526358462896305
141 	 0.5436471604431379
130 	 0.5279344148536391
151 	 0.5222841768221841
8 	 0.5021957027586691
139 	 0.49189952651725943
44 	 0.4917477111230456
264 	 0.481176331749483
mean_pitch 	 0.4601084564063069
93 	 0.4403577784422246
135 	 0.43097919542108554
262 	 0.4301818563604901
17 	 0.4271651639826399
235 	 0.42163908181202975
81 	 0.4139857040607989
265 	 0.4101019124618794
89 	 0.40972774839082976
156 	 0.4071865218956025
169 	 0.40567861047827297
229 	 0.40475568851814725
3 	 0.39947196820334296
shimmer 	 0.3991288269389981
132 	 0.3934536034966219
54 	 0.38772233449510946
124 	 0.36715498024582893
158 	 0.36343338922226187
46 	 0.35776276725857714
21 	 0.35635133713587175
80 	 0.3511001064067799
160 	 0.347997801782072
85 	 0.3458310010267588
12 	 0.3432281731861162
266 	 0.34282472849740464
211 	 0.3396584374521601
206 	 0.3389916100361672
147 	 0.33740925888281065
261 	 0.3359071214894201
194 	 0.33443863873133833
193 	 0.3343678766250728
129 	 0.3240211303300873
99 	 0.3227195714765393
1 	 0.31827597847455696
10 	 0.3104637616606798
219 	 0.30946173080696376
253 	 0.30884508684129586
144 	 0.30426148099026845
202 	 0.29824245732644444
275 	 0.298118621693229
142 	 0.29711548220178463
210 	 0.2945845588336138
91 	 0.29314683345615783
215 	 0.29051477785041463
136 	 0.2887313436352323
178 	 0.28599766148272765
223 	 0.2853652919979002
276 	 0.2832996186894618
164 	 0.2827105324712941
50 	 0.2826514371714365
84 	 0.2807149183997726
92 	 0.2804043717514823
31 	 0.27766044108985016
173 	 0.2771074835171342
126 	 0.2760137521982563
88 	 0.27598148411554974
152 	 0.27451686296441763
192 	 0.2732124946392677
28 	 0.27304545515172457
208 	 0.2718327695418475
268 	 0.2699523764189085
170 	 0.26926077675107524
98 	 0.2685640341692105
0 	 0.26850741745141476
13 	 0.2680118575746959
188 	 0.26607940361631577
90 	 0.26482930475966815
27 	 0.26448673255194627
213 	 0.2643468624993265
14 	 0.2633525566675698
97 	 0.2628962949898492
267 	 0.26129168668375047
274 	 0.2612406144108482
15 	 0.2609606943417462
277 	 0.26066417416145915
209 	 0.2605841239238569
242 	 0.25946987596286797
4 	 0.2573600676832114
20 	 0.2561642501549073
186 	 0.25589113375321565
19 	 0.25513579665477737
106 	 0.25481274516629665
238 	 0.25300273298838905
105 	 0.2523581972631804
171 	 0.2518855491752623
37 	 0.25089394996195347
149 	 0.2489742783690266
9 	 0.24886290566374
145 	 0.24862749448882113
157 	 0.2468054667701757
29 	 0.2460568751137383
128 	 0.24572161750750612
243 	 0.24551289682894756
18 	 0.244236716082894
108 	 0.24421234141560466
78 	 0.2435114113273708
122 	 0.24328275369654276
155 	 0.2417044590858915
271 	 0.24106305826164487
41 	 0.240212826451346
62 	 0.23931937646786494
64 	 0.239142943472117
spectral_centroid_mean 	 0.2385507697148725
239 	 0.2355972230433502
23 	 0.23475264031552195
278 	 0.2335764142407516
177 	 0.23305474242252094
179 	 0.23218596446683581
5 	 0.23074194147901997
172 	 0.22946562973223686
16 	 0.2284556887497608
56 	 0.22783732799844442
216 	 0.22753736576749806
159 	 0.2259215700024773
57 	 0.22560591311242942
6 	 0.2247466949819388
137 	 0.2239420546964835
30 	 0.22264360830998278
49 	 0.21970617546533872
52 	 0.21927268812662534
244 	 0.2183594096149099
67 	 0.2178338062772832
69 	 0.21676499294086155
95 	 0.21606481012099754
zcr_mean 	 0.21586585085326604
22 	 0.21450612727997673
119 	 0.2141515697471545
285 	 0.2138146465831708
184 	 0.21235481638906553
249 	 0.21165398890769252
48 	 0.21136434570161283
energy 	 0.2113142414276412
72 	 0.2109523110606261
207 	 0.2104445950364861
96 	 0.20743928885293833
162 	 0.20740146008949345
60 	 0.20724610898256438
282 	 0.2050774276517499
75 	 0.20438973254016654
175 	 0.20416749281040675
68 	 0.2030995997959159
269 	 0.20293774725558353
163 	 0.2026576498223985
87 	 0.2024283018073414
226 	 0.20230729683905962
203 	 0.20086826317586495
58 	 0.20054287275933355
118 	 0.2001630817586872
32 	 0.20003737079797743
185 	 0.19837172885072055
191 	 0.19820491197617246
298 	 0.1980382533293361
252 	 0.19756387839519243
63 	 0.19724842560865122
222 	 0.19480093944451146
117 	 0.19259997951882196
270 	 0.18982854193055504
245 	 0.18718749417958785
221 	 0.18667181767946142
220 	 0.18462701864069342
43 	 0.18281514435196758
131 	 0.1823261229597577
153 	 0.18191023723470318
205 	 0.18154104639373084
77 	 0.1813052680075911
112 	 0.18120352025047876
217 	 0.18057579762825415
259 	 0.18034399689199845
143 	 0.17936964815570156
195 	 0.17926741102179383
232 	 0.1789947532635699
168 	 0.1786087684363543
71 	 0.1780846336341626
26 	 0.17735381732427455
70 	 0.17661538111316394
114 	 0.17613220060494975
198 	 0.17598234249797606
237 	 0.17540544636237632
248 	 0.17528543429302904
257 	 0.17342792895157738
109 	 0.17315250338702595
107 	 0.17292407147943922
256 	 0.172399831967897
66 	 0.17206331721759432
2 	 0.17203416944906902
39 	 0.17134718324338152
127 	 0.1711446325425018
150 	 0.17054811926440078
tempo 	 0.1701611458928828
180 	 0.1700609335183746
292 	 0.1698416434199399
101 	 0.16984011380871966
201 	 0.169494318627792
297 	 0.16946624752504313
61 	 0.1690945701154647
294 	 0.16851399549747903
116 	 0.16819808806629197
204 	 0.16783757858665005
234 	 0.16692316843692903
290 	 0.16679215429101943
36 	 0.16615049415427485
33 	 0.16588451436128587
133 	 0.16527331386939376
236 	 0.16486093554706419
218 	 0.16469488237897986
83 	 0.16427591695044952
227 	 0.16404146801729017
123 	 0.16323241876471067
296 	 0.1621757618015349
176 	 0.16207426713142256
65 	 0.1607989737553333
263 	 0.16024377281723573
254 	 0.1597527157200513
51 	 0.15845755997966404
102 	 0.1576729167731243
284 	 0.1573611953640919
281 	 0.15627558119788926
189 	 0.1559524378050498
74 	 0.1548965679958805
291 	 0.15406061628581352
224 	 0.15349515594632251
200 	 0.15268437908728053
34 	 0.15243896269864468
174 	 0.15084727626928263
230 	 0.14852046006603015
279 	 0.14850603842304638
255 	 0.14843497497227026
167 	 0.14796246953554235
42 	 0.1465370573349668
258 	 0.14623787534793767
199 	 0.14372998769447382
250 	 0.14368383404128057
283 	 0.14320946843201385
212 	 0.14279635988342332
140 	 0.14124386437592282
273 	 0.1411039312694946
7 	 0.1401558336906695
197 	 0.14009524665324655
295 	 0.1397732786661461
272 	 0.13726737001008066
103 	 0.13665413690831987
241 	 0.13657437447912907
165 	 0.1361624308878662
73 	 0.13569601955464627
55 	 0.13459681909942806
113 	 0.13394679062655288
299 	 0.132425752866536
161 	 0.13232210918051412
25 	 0.1320314978928955
59 	 0.1318610967599412
293 	 0.13145978934277744
288 	 0.13107055542208212
24 	 0.13034199515558334
134 	 0.13015425909383974
82 	 0.12982374705907362
182 	 0.1294230144725488
53 	 0.12916884394132488
247 	 0.12647306614285228
76 	 0.12592695893581735
260 	 0.12497821628287714
166 	 0.12474767665792773
47 	 0.12445863748707428
286 	 0.12434729717325735
79 	 0.12300989505494703
225 	 0.12251712826938418
138 	 0.12156124662259628
154 	 0.12152858115628003
187 	 0.12151028380942339
110 	 0.1214243032061374
287 	 0.12111462983574484
35 	 0.11986366776788433
289 	 0.11930894925985176
228 	 0.11865314737222393
251 	 0.11467555019875723
233 	 0.11417582218213072
240 	 0.11384949071283705
214 	 0.11243552466549461
125 	 0.11179724937541224
104 	 0.11168809470783604
181 	 0.11162413640068428
38 	 0.10977645663358428
111 	 0.10752127565547341
280 	 0.10734167438831545
115 	 0.10714089580974619
11 	 0.10670544332453989
45 	 0.10664175517201735
231 	 0.10573773445078846
246 	 0.08769052809700541
ethnicity 	 0.00040527918971533614

In [155]:
cross_val_score(RandomForestRegressor(n_jobs=-1), male, male_age, cv=10, scoring='neg_mean_absolute_error').mean()

np.float64(-7.653621046500791)

## Consegna risposte

In [205]:
data_evaluation = pd.read_csv('../data/evaluation.csv', index_col=0)
data_evaluation['path'] = data_evaluation['path'].map(lambda x: x.split('/')[1]) # int(x.split('/')[1].split('.')[0]))
display(data_evaluation)

,sampling_rate,gender,ethnicity,mean_pitch,max_pitch,min_pitch,jitter,shimmer,energy,zcr_mean,spectral_centroid_mean,tempo,hnr,num_words,num_characters,num_pauses,silence_duration,path
Id,,,,,,,,,,,,,,,,,,
0,22050,male,spanish,1056.91740,3945.1610,145.38750,0.022082,0.171076,0.003136,0.032963,1549.607050,[80.74951172],-116.662338,69,281,2,38.198503,1.wav
1,22050,male,xiang,1231.84570,3999.1720,145.56432,0.026571,0.132585,0.006783,0.123895,2344.817369,[89.10290948],-78.253824,69,281,27,29.605442,2.wav
2,22050,male,igbo,958.29065,3445.4490,145.67374,0.018044,0.096289,0.004478,0.089149,1939.574896,[123.046875],-71.630742,6,22,2,2.275556,3.wav
3,22050,female,spanish,1396.54170,3998.8948,145.41223,0.027290,0.088901,0.014893,0.097054,1832.059113,[123.046875],-101.533013,69,281,31,22.151837,4.wav
4,22050,male,spanish,1633.86770,3999.7632,145.36313,0.021621,0.103855,0.001369,0.140950,2534.611168,[112.34714674],-134.914070,69,281,35,22.430476,5.wav
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,22050,male,igbo,570.62740,3900.6730,145.67577,0.018842,0.079197,0.004545,0.072083,1946.502158,[112.34714674],-42.895295,6,15,1,1.861950,687.wav
687,22050,male,igbo,974.13965,3919.0024,145.90408,0.024367,0.117492,0.000878,0.076900,3319.620800,[112.34714674],-144.881089,7,22,1,4.876190,688.wav
688,22050,female,serbian,1113.27650,3999.3510,145.38307,0.020637,0.089355,0.009148,0.095613,1973.127197,[112.34714674],-73.559944,69,281,15,25.541950,689.wav
689,22050,male,spanish,1759.17420,3999.4610,145.56773,0.026118,0.106429,0.003707,0.141474,2137.517812,[117.45383523],-93.562873,69,281,10,20.967619,690.wav
690,22050,male,igbo,779.53890,3972.4630,147.44424,0.010952,0.108114,0.003370,0.083540,2530.285199,[184.5703125],-35.776665,5,19,1,1.230658,691.wav

In [206]:
np.unique(data_evaluation['sampling_rate'].values)

array([22050])

In [207]:
SAMPLE_RATE = 22050
num_time_buckets = 20

In [200]:
audio_files_evaluation = os.listdir('../data/audios_evaluation')
audio_arrays_evaluation,mfccs_evaluation,time_sampl_evaluation = load_data(audio_files_evaluation, '../data/audios_evaluation/', SAMPLE_RATE)

In [208]:
standardized_mfccs_evaluation = standardize_all(mfccs_evaluation, num_time_buckets)
reshaped_mfccs_evaluation = reshape_all(standardized_mfccs_evaluation)

In [209]:
display(reshaped_mfccs_evaluation)

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
1.wav,-409.024384,-318.300507,-356.190277,-345.002319,-337.278931,-334.057831,-357.991608,-326.944092,-306.628845,-350.886414,...,3.988764,1.971522,4.218048,2.856964,0.434794,1.786844,4.884138,7.342025,6.462479,1.600923
10.wav,-435.284241,-392.018524,-248.948151,-323.007416,-292.441101,-270.305969,-284.768127,-329.105835,-327.972534,-353.197693,...,-5.979064,-5.135306,3.936126,0.141418,-5.740375,-13.966771,-5.430674,-2.823639,-10.169382,-2.961752
100.wav,-293.302338,-247.493042,-293.399414,-261.878693,-259.596832,-272.239227,-267.624451,-311.161499,-248.529968,-275.995758,...,14.765183,14.073303,12.891003,8.772925,11.083576,10.430563,14.053826,11.543507,11.924887,10.976063
101.wav,-193.993469,-331.810791,-270.091370,-290.040497,-326.564789,-264.394196,-321.724152,-238.821533,-321.110321,-241.872086,...,8.019660,7.337913,9.528759,6.420187,6.243932,4.817814,8.012930,5.655083,5.977262,7.757629
102.wav,-431.241058,-335.702271,-277.690338,-265.180511,-357.530884,-275.078308,-324.168732,-250.916199,-342.306335,-235.404755,...,-13.446664,-14.555564,-13.896852,-6.870616,-10.348890,-13.119678,-8.803543,-8.120754,-8.011740,-12.725560
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95.wav,-519.660828,-312.015198,-345.898254,-301.076508,-305.187042,-230.281097,-357.826508,-327.026001,-359.214020,-415.862976,...,0.992612,7.384030,1.896030,-11.600630,-2.917705,6.524923,6.019863,13.066234,7.906710,11.046993
96.wav,-335.466797,-317.808655,-165.252213,-214.704208,-170.736435,-202.559998,-216.286987,-148.046417,-180.815384,-172.436188,...,0.697124,4.973277,-6.263444,-3.027616,0.056703,2.821440,-2.695671,1.973516,3.052486,0.571430
97.wav,-503.112793,-443.052155,-453.366699,-453.388092,-230.930328,-284.111115,-296.293030,-288.297302,-323.740601,-304.597900,...,7.643392,-8.778545,-5.423125,-2.170265,-9.004732,-16.067131,-6.832082,0.283662,-1.104228,0.164042
98.wav,-261.113708,-330.292542,-284.257782,-275.578186,-321.897217,-259.656433,-314.730774,-286.421936,-298.456909,-323.157501,...,0.490386,3.241124,-0.128632,4.476760,8.151598,0.362155,2.285372,4.306463,8.140712,1.063711
99.wav,-376.093353,-327.850189,-333.338013,-386.929352,-339.652039,-340.448608,-366.211273,-382.069824,-347.990570,-309.733185,...,-20.420902,-14.785982,-16.894455,-15.205720,-16.037922,-21.518303,-16.950750,-15.857066,-16.701094,-16.609846

In [204]:
temp = reshaped_mfccs_evaluation.reset_index()
temp['index'] = temp['index'].map(lambda x: int(x.split('.')[0])-1)
reshaped_mfccs_evaluation_ind = temp.set_index('index').sort_index()
display(reshaped_mfccs_evaluation_ind)

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
index,,,,,,,,,,,,,,,,,,,,,
0,-409.024384,-318.300507,-356.190277,-345.002319,-337.278931,-334.057831,-357.991608,-326.944092,-306.628845,-350.886414,...,3.988764,1.971522,4.218048,2.856964,0.434794,1.786844,4.884138,7.342025,6.462479,1.600923
1,-336.617706,-261.725800,-240.710938,-344.066650,-297.420715,-252.167053,-258.892456,-270.511047,-272.087616,-254.859573,...,5.123708,5.566287,8.486043,4.639581,5.483193,0.815799,1.230392,4.926414,3.831308,4.204085
2,-445.425537,-434.862152,-305.619904,-194.119293,-183.565063,-196.765488,-183.358307,-205.783173,-259.249573,-177.744232,...,2.637795,-2.742330,-8.127054,4.732387,-2.522875,-0.810776,-1.422979,3.038233,7.989042,-7.020223
3,-313.318878,-274.385010,-246.486557,-273.996124,-306.219360,-255.408829,-288.595795,-251.849548,-294.436462,-270.199249,...,-6.895550,-2.852007,-1.263843,-2.992028,-2.460367,-3.775903,-2.890278,-1.230701,-2.002275,-4.992485
4,-377.444305,-336.198242,-347.945862,-377.295685,-384.000092,-390.826843,-382.165619,-291.606873,-362.531250,-321.496216,...,-2.559943,-1.841891,-3.630640,-0.582794,-4.660622,-2.600523,0.338119,3.084750,-0.355871,-0.955362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
686,-525.936646,-463.163910,-285.372253,-173.060684,-185.194565,-265.145233,-264.845703,-319.030701,-299.257751,-263.070770,...,-14.276779,-11.735075,-6.766476,-9.147609,-13.228241,-9.561797,-3.902442,1.958264,-1.463599,-5.913436
687,-478.394135,-451.433533,-442.786377,-448.233002,-445.452393,-452.258240,-444.285889,-450.208344,-451.439697,-339.876648,...,-11.725979,-12.265416,1.553086,-2.849491,0.542458,3.470596,-0.493849,-7.555924,-2.488146,8.529310
688,-271.483917,-239.948807,-328.058838,-259.273132,-248.833664,-284.503174,-261.941864,-278.541779,-265.497742,-304.869049,...,-4.667590,-8.239069,-4.484377,-1.738832,-3.900306,-2.096578,-5.937396,-2.954125,-8.934360,-4.939095
689,-221.711868,-276.007629,-246.053497,-290.043640,-275.951416,-243.929077,-273.607330,-248.430008,-240.135300,-244.987457,...,-3.350654,-4.871803,-2.361799,-2.318775,-3.458122,-8.727138,-4.239640,-2.740751,-1.829307,-3.902994
690,-407.711792,-286.518005,-231.240723,-219.728027,-222.425064,-252.263733,-223.435852,-296.289307,-185.870300,-209.343445,...,-4.804996,-10.516898,-22.995237,-19.365223,-15.462652,-8.665983,-1.901581,-4.755772,2.619517,1.946403

In [210]:
data_evaluation.loc[data_evaluation['num_characters']==281,'ethnicity'] = 1 # and data_evaluation['num_words']==69),'ethnicity'] = 1
data_evaluation.loc[data_evaluation['num_characters']!=281,'ethnicity'] = 0 # or data_evaluation['num_words']!=69),'ethnicity'] = 0
clean_data_evaluation = data_evaluation.drop(columns=['num_words','num_characters','num_pauses','sampling_rate','max_pitch','min_pitch'])
clean_data_evaluation['tempo'] = clean_data_evaluation['tempo'].map(lambda x: float(x[1:-1]))
display(clean_data_evaluation)

,gender,ethnicity,mean_pitch,jitter,shimmer,energy,zcr_mean,spectral_centroid_mean,tempo,hnr,silence_duration,path
Id,,,,,,,,,,,,
0,male,1,1056.91740,0.022082,0.171076,0.003136,0.032963,1549.607050,80.749512,-116.662338,38.198503,1.wav
1,male,1,1231.84570,0.026571,0.132585,0.006783,0.123895,2344.817369,89.102909,-78.253824,29.605442,2.wav
2,male,0,958.29065,0.018044,0.096289,0.004478,0.089149,1939.574896,123.046875,-71.630742,2.275556,3.wav
3,female,1,1396.54170,0.027290,0.088901,0.014893,0.097054,1832.059113,123.046875,-101.533013,22.151837,4.wav
4,male,1,1633.86770,0.021621,0.103855,0.001369,0.140950,2534.611168,112.347147,-134.914070,22.430476,5.wav
...,...,...,...,...,...,...,...,...,...,...,...,...
686,male,0,570.62740,0.018842,0.079197,0.004545,0.072083,1946.502158,112.347147,-42.895295,1.861950,687.wav
687,male,0,974.13965,0.024367,0.117492,0.000878,0.076900,3319.620800,112.347147,-144.881089,4.876190,688.wav
688,female,1,1113.27650,0.020637,0.089355,0.009148,0.095613,1973.127197,112.347147,-73.559944,25.541950,689.wav
689,male,1,1759.17420,0.026118,0.106429,0.003707,0.141474,2137.517812,117.453835,-93.562873,20.967619,690.wav
690,male,0,779.53890,0.010952,0.108114,0.003370,0.083540,2530.285199,184.570312,-35.776665,1.230658,691.wav

In [214]:
joined_data_evaluation = clean_data_evaluation.join(reshaped_mfccs_evaluation, on='path').drop(columns=['path'])

In [190]:
full_data_evaluation = pd.concat([clean_data_evaluation, reshaped_mfccs_evaluation_ind], axis=1)
display(full_data_evaluation)

,gender,ethnicity,mean_pitch,jitter,shimmer,energy,zcr_mean,spectral_centroid_mean,tempo,hnr,...,290,291,292,293,294,295,296,297,298,299
1,male,1,1056.91740,0.022082,0.171076,0.003136,0.032963,1549.607050,80.749512,-116.662338,...,3.988764,1.971522,4.218048,2.856964,0.434794,1.786844,4.884138,7.342025,6.462479,1.600923
2,male,1,1231.84570,0.026571,0.132585,0.006783,0.123895,2344.817369,89.102909,-78.253824,...,5.123708,5.566287,8.486043,4.639581,5.483193,0.815799,1.230392,4.926414,3.831308,4.204085
3,male,0,958.29065,0.018044,0.096289,0.004478,0.089149,1939.574896,123.046875,-71.630742,...,2.637795,-2.742330,-8.127054,4.732387,-2.522875,-0.810776,-1.422979,3.038233,7.989042,-7.020223
4,female,1,1396.54170,0.027290,0.088901,0.014893,0.097054,1832.059113,123.046875,-101.533013,...,-6.895550,-2.852007,-1.263843,-2.992028,-2.460367,-3.775903,-2.890278,-1.230701,-2.002275,-4.992485
5,male,1,1633.86770,0.021621,0.103855,0.001369,0.140950,2534.611168,112.347147,-134.914070,...,-2.559943,-1.841891,-3.630640,-0.582794,-4.660622,-2.600523,0.338119,3.084750,-0.355871,-0.955362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
687,male,0,570.62740,0.018842,0.079197,0.004545,0.072083,1946.502158,112.347147,-42.895295,...,-14.276779,-11.735075,-6.766476,-9.147609,-13.228241,-9.561797,-3.902442,1.958264,-1.463599,-5.913436
688,male,0,974.13965,0.024367,0.117492,0.000878,0.076900,3319.620800,112.347147,-144.881089,...,-11.725979,-12.265416,1.553086,-2.849491,0.542458,3.470596,-0.493849,-7.555924,-2.488146,8.529310
689,female,1,1113.27650,0.020637,0.089355,0.009148,0.095613,1973.127197,112.347147,-73.559944,...,-4.667590,-8.239069,-4.484377,-1.738832,-3.900306,-2.096578,-5.937396,-2.954125,-8.934360,-4.939095
690,male,1,1759.17420,0.026118,0.106429,0.003707,0.141474,2137.517812,117.453835,-93.562873,...,-3.350654,-4.871803,-2.361799,-2.318775,-3.458122,-8.727138,-4.239640,-2.740751,-1.829307,-3.902994
691,male,0,779.53890,0.010952,0.108114,0.003370,0.083540,2530.285199,184.570312,-35.776665,...,-4.804996,-10.516898,-22.995237,-19.365223,-15.462652,-8.665983,-1.901581,-4.755772,2.619517,1.946403

In [191]:
female_full_data_evaluation = full_data_evaluation[full_data_evaluation['gender']=='female'].drop(columns=['gender'])
male_full_data_evaluation = full_data_evaluation[full_data_evaluation['gender']=='male'].drop(columns=['gender'])
female_full_data_evaluation.columns = female_full_data_evaluation.columns.astype(str)
male_full_data_evaluation.columns = male_full_data_evaluation.columns.astype(str)

In [192]:
ypred_female = RandomForestRegressor(n_jobs=-1).fit(female, female_age).predict(female_full_data_evaluation)
ypred_male = RandomForestRegressor(n_jobs=-1).fit(male, male_age).predict(male_full_data_evaluation)

In [193]:
ypred_female_series = pd.Series(ypred_female, name='Predicted', index=female_full_data_evaluation.index)
ypred_male_series = pd.Series(ypred_male, name='Predicted', index=male_full_data_evaluation.index)
ypred = pd.concat([ypred_female_series, ypred_male_series]).sort_index()
display(ypred)

1      29.770
2      29.230
3      22.140
4      31.540
5      34.080
        ...
687    20.690
688    25.000
689    27.365
690    41.330
691    19.700
Name: Predicted, Length: 690, dtype: float64

In [196]:
pd.DataFrame(ypred, index=data_evaluation.index).to_csv('submissionMaddalena.csv') # hits 10.367 above naive baseline